name: Deploy to QA Environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to QA with SST
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: |
          echo "MOVIE_DB_API_KEY=${{ vars.MOVIE_DB_API_KEY }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with SST
        run: npx sst deploy --stage qa